#!/bin/bash
#
# in order to configure git locally to use the new hook:

# ```sh
# git config core.hooksPath "./.git_hooks"
# ```

CARGO_FMT="cargo +stable fmt"
CLIPPY="cargo +stable clippy"

$CARGO_FMT --version &>/dev/null
if [ $? != 0 ]; then
    printf "[pre_commit] \033[0;31merror\033[0m: \"$CARGO_FMT\" not available?\n"
    exit 1
fi

$CLIPPY --version &>/dev/null
if [ $? != 0 ]; then
    printf "[pre_commit] \033[0;31merror\033[0m: \"$CLIPPY\" not available?\n"
    exit 1
fi

# ---

$CARGO_FMT -- --check
result=$?

printf "[pre_commit] $CARGO_FMT → "
if [ $result != 0 ]; then
    printf "\033[0;31merror\033[0m \n"
	exit $result
else
    printf "\033[0;32mOK\033[0m \n"
fi

$CLIPPY
result=$?

printf "[pre_commit] $CLIPPY → "
if [ $result != 0 ]; then
    printf "\033[0;31merror\033[0m \n"
else
    printf "\033[0;32mOK\033[0m \n"
fi

exit $result
